const assert = require('node:assert/strict');
const fs = require('node:fs');
const ts = require('typescript');
const vm = require('node:vm');
const source = fs.readFileSync(require.resolve('../utils/chatPeerStatus.ts'), 'utf8');
const output = ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 } }).outputText;
const exportsObject = {};
let request;
vm.runInNewContext(output, { exports: exportsObject, AbortController, setTimeout, clearTimeout, fetch: (...args) => request(...args) });
const load = exportsObject.loadChatPeerStatus;
const args = { baseUrl: 'https://example.test', peerId: '42', getToken: async () => 'test-token', timeoutMs: 25 };
(async () => {
  let calls = 0;
  request = async (url, options) => {
    calls++;
    assert.equal(url, 'https://example.test/api/messages/peers/42');
    assert.equal(options.headers.Authorization, 'Bearer test-token');
    return { ok: true, json: async () => ({ needsGift: false, online: true, lastSeen: 123 }) };
  };
  assert.equal((await load(args)).needsGift, false);
  await assert.rejects(load({ ...args, getToken: async () => null }), /sign in/);
  assert.equal(calls, 1);
  await assert.rejects(load({ ...args, getToken: () => new Promise(() => {}) }), /load chat status/);
  let requestSignal;
  request = (_, options) => { requestSignal = options.signal; return new Promise(() => {}); };
  await assert.rejects(load(args), /load chat status/);
  assert.equal(requestSignal.aborted, true);
  request = async () => ({ ok: true, json: () => new Promise(() => {}) });
  await assert.rejects(load(args), /load chat status/);
  request = async () => ({ ok: false });
  await assert.rejects(load(args), /load chat status/);
  const controller = new AbortController();
  const cancelled = load({ ...args, signal: controller.signal, getToken: () => new Promise(() => {}) });
  controller.abort();
  await assert.rejects(cancelled, /cancelled/);
  request = async () => ({ ok: true, json: async () => ({ needsGift: true }) });
  assert.equal((await load(args)).needsGift, true, 'Recovery must retain the gift requirement for unopened chats');
  console.log('PASS: chat status success, auth, token/request/body deadlines, abort, HTTP failure and retry recovery.');
})().catch(error => { console.error(error); process.exitCode = 1; });
