const assert = require('node:assert/strict');
const fs = require('node:fs');
const ts = require('typescript');
const vm = require('node:vm');
const source = fs.readFileSync(require.resolve('../../../lib/api-client-react/src/custom-fetch.ts'), 'utf8');
const output = ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 } }).outputText;
const api = {};
let request;
vm.runInNewContext(output, { exports: api, AbortController, Headers, Request, URL, setTimeout, clearTimeout, fetch: (...args) => request(...args) });
const options = { timeoutMs: 20, method: 'POST', body: '{}' };
(async () => {
  let calls = 0, resolveToken;
  request = async () => { calls++; return new Response('{}', { headers: { 'content-type': 'application/json' } }); };
  api.setAuthTokenGetter(() => new Promise(resolve => { resolveToken = resolve; }));
  await assert.rejects(api.customFetch('/api/streams', options), /timed out/);
  resolveToken('late-token');
  await new Promise(resolve => setTimeout(resolve, 0));
  assert.equal(calls, 0, 'A late auth token must not create a stream after timeout');
  api.setAuthTokenGetter(() => 'test-token');
  let signal;
  request = (_, opts) => { signal = opts.signal; return new Promise(() => {}); };
  await assert.rejects(api.customFetch('/api/streams', options), /timed out/);
  assert.equal(signal.aborted, true);
  request = async () => ({ ok: true, status: 200, headers: new Headers({ 'content-type': 'application/json' }), text: () => new Promise(() => {}) });
  await assert.rejects(api.customFetch('/api/streams', options), /timed out/);
  request = async () => new Response('{"error":"Denied"}', { status: 403, headers: { 'content-type': 'application/json' } });
  await assert.rejects(api.customFetch('/api/streams', options), /Denied/);
  const controller = new AbortController();
  controller.abort();
  request = async () => { throw new Error('Must not fetch'); };
  await assert.rejects(api.customFetch('/api/streams', { ...options, signal: controller.signal }), /cancelled/);
  request = async (_, opts) => {
    assert.equal(opts.headers.get('authorization'), 'Bearer test-token');
    assert.equal(opts.timeoutMs, undefined);
    return new Response('{"channelId":"test"}', { headers: { 'content-type': 'application/json' } });
  };
  assert.equal((await api.customFetch('/api/streams', options)).channelId, 'test');
  assert.equal((await api.customFetch('/api/streams')).channelId, 'test', 'Requests without an opt-in deadline still work');
  console.log('PASS: startup auth/fetch/body deadlines, late auth protection, abort, server error, success and retry.');
})().catch(error => { console.error(error); process.exitCode = 1; });
