const escapeHtml = (value: string) => value.replace(/[&<>"']/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]!);
export function verificationPage(nonce: string, privacyUrl?: string) {
  let privacy = "";
  try { const url = new URL(privacyUrl ?? ""); if (url.protocol === "https:" && !url.username && !url.password) privacy = escapeHtml(url.href); } catch { /* Unconfigured: no capture can start. */ }
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Verify your age · Pulse</title>
<style nonce="${nonce}">*{box-sizing:border-box}body{margin:0;background:#10111b;color:#f6f6fa;font:17px/1.6 system-ui,sans-serif}main{max-width:580px;margin:6vh auto;padding:28px}h1{line-height:1.2;font-size:32px}.brand{color:#ff638d;font-weight:800;letter-spacing:2px}section{background:#1d1e2d;padding:24px;border-radius:20px;margin:24px 0}button,.button{display:block;width:100%;background:#ff638d;color:#17121b;border:0;border-radius:12px;padding:14px;font:700 17px system-ui;cursor:pointer;text-align:center;text-decoration:none;margin:18px 0}button:disabled{opacity:.5;cursor:wait}a{color:#ff99b8}label{display:flex;gap:12px;align-items:flex-start}input{width:22px;height:22px;flex-shrink:0;margin-top:4px}#error{color:#ffb7bc}small{color:#c8c8d9}[hidden]{display:none!important}:focus-visible{outline:3px solid #fff;outline-offset:4px}</style></head><body><main>
<a class="brand" href="/api/site/">Pulse</a><h1>Verify you're 18+</h1><p>Confirm your age to access features reserved for verified adults.</p>
<p id="account"></p><p id="test" hidden>Sandbox test account — this is a test verification.</p><p id="status" role="status" aria-live="polite">Loading your account…</p><p id="error" role="alert"></p>
<section id="start-panel" hidden><h2>Identity and age check</h2><p>Didit will ask for an identity document and a selfie to check your age, match your face, and check that you are present. Pulse receives the verification result. We do not copy your document or selfie into Pulse storage.</p>
<p>Read ${privacy ? `<a href="${privacy}" target="_blank" rel="noopener noreferrer">Pulse's privacy notice</a> and ` : ""}<a href="https://didit.me/terms/privacy-policy/" target="_blank" rel="noopener noreferrer">Didit's privacy notice</a> before continuing.</p>
<label><input type="checkbox" id="consent"><span>I have read the privacy information and agree to the processing of my identity document and selfie for identity and age verification.</span></label><button id="start">Continue to verification</button></section>
<section id="mature-panel" hidden><h2>Your content preference</h2><p>Verification does not turn on mature content. Choose separately whether to show eligible mature content. You can turn this off here later.</p><label><input type="checkbox" id="mature"><span>Show mature content (18+)</span></label><button id="save">Save preference</button><p id="saved" role="status" aria-live="polite"></p></section>
<button id="refresh" hidden>Check verification status</button><a class="button" href="mobile://verification">Return to Pulse</a><small>If the app does not open, switch back to Pulse. You can reopen this page from Account → Age verification.</small>
<script nonce="${nonce}">
const root='/api/verification/web';let csrf='';let busy=false;let pending=false;
const el=id=>document.getElementById(id);
async function request(path,body){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),15000);try{const r=await fetch(root+path,{signal:controller.signal,method:body?'POST':'GET',credentials:'same-origin',headers:{'Content-Type':'application/json','X-Verification-CSRF':csrf},...(body?{body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok){if(r.status===401){pending=false;csrf='';for(const id of ['start-panel','mature-panel','refresh'])el(id).hidden=true;el('status').textContent='Open this page from your Pulse account.';throw Error('In Pulse, go to Account → Age verification and tap Verify now to open your personal link.');}throw Error(d.error||'Please try again.');}return d;}catch(e){if(e.name==='AbortError')throw Error('The request timed out. Please try again.');throw e;}finally{clearTimeout(timer);}}

function render(d){pending=d.status==='pending';el('start-panel').hidden=d.isVerified||d.status==='review_needed';el('mature-panel').hidden=!d.isVerified;el('mature').checked=!!d.matureContentEnabled;el('refresh').hidden=false;el('status').textContent=d.isVerified?'Your age is verified.':d.status==='pending'?'Your verification is in progress.':d.status==='review_needed'?'Your verification needs review. Please contact Pulse support.':d.status==='failed'?'Verification was not approved. You must be 18 or older and use your own valid identity document.':'Your age has not been verified.';}
async function run(fn){if(busy)return;busy=true;el('error').textContent='';el('refresh').textContent='Checking verification status…';for(const b of document.querySelectorAll('button'))b.disabled=true;try{await fn();}catch(e){el('error').textContent=e.message;if(!csrf)el('status').textContent='Reopen verification from your Pulse account to continue.';}finally{busy=false;el('refresh').textContent='Check verification status';for(const b of document.querySelectorAll('button'))b.disabled=false;}}
el('start').onclick=()=>run(async()=>{if(!el('consent').checked)throw Error('Please read and accept the verification notice first.');const d=await request('/start',{consent:true,consentVersion:'pulse-id-18-v1'});location.assign(d.url);});
el('save').onclick=()=>run(async()=>{render(await request('/preference',{enabled:el('mature').checked,version:'pulse-mature-v1'}));el('saved').textContent='Preference saved.';});
el('refresh').onclick=()=>run(async()=>{render(await request('/refresh',{}));el('status').textContent+=' Status checked.';});
run(async()=>{const ticket=new URLSearchParams(location.hash.slice(1)).get('ticket');const returning=new URLSearchParams(location.search).has('verificationSessionId');history.replaceState(null,'',location.pathname);if(ticket)await request('/exchange',{ticket});const d=await request('/status');csrf=d.csrf;el('account').textContent='Pulse account '+d.accountId;el('test').hidden=d.environment!=='sandbox';render(d);if(returning)render(await request('/refresh',{}));});
let polls=0;setInterval(()=>{if(pending&&!document.hidden&&polls++<40)run(async()=>render(await request('/refresh',{})));},15000);
</script></main></body></html>`;
}
