const escapeHtml = (value: string) => value.replace(/[&<>"']/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]!);
export function verificationPage(nonce: string, privacyUrl?: string) {
  let privacy = "";
  try { const url = new URL(privacyUrl ?? ""); if (url.protocol === "https:" && !url.username && !url.password) privacy = escapeHtml(url.href); } catch { /* Unconfigured: no capture can start. */ }
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Verify your age · Pulse</title>
<style nonce="${nonce}">*{box-sizing:border-box}body{margin:0;background:#10111b;color:#f6f6fa;font:17px/1.6 system-ui,sans-serif}main{max-width:580px;margin:6vh auto;padding:28px}h1{line-height:1.2;font-size:32px}h1 em{font-style:normal;color:#ff7fa7}h3{font-size:19px}.brand{color:#ff638d;font-weight:800;letter-spacing:2px}section{background:#1d1e2d;padding:24px;border-radius:20px;margin:24px 0}button,.button{display:block;width:100%;background:#ff638d;color:#17121b;border:0;border-radius:12px;padding:14px;font:700 17px system-ui;cursor:pointer;text-align:center;text-decoration:none;margin:18px 0}button:disabled{opacity:.5;cursor:wait}a{color:#ff99b8}label{display:flex;gap:12px;align-items:flex-start}input{width:22px;height:22px;flex-shrink:0;margin-top:4px}.toggle-row{align-items:center;justify-content:space-between;min-height:48px;cursor:pointer}.toggle-row input{appearance:none;-webkit-appearance:none;width:52px;height:30px;margin:0;position:relative;border:1px solid #9292a5;border-radius:999px;background:#525268;cursor:pointer}.toggle-row input:before{content:"";position:absolute;width:22px;height:22px;left:3px;top:3px;border-radius:50%;background:#fff}.toggle-row input:checked{background:#ff638d;border-color:#ff638d}.toggle-row input:checked:before{left:25px}.verified-status{font-size:28px;font-weight:800;line-height:1.2;color:#4ade80}#error{color:#ffb7bc}small{color:#c8c8d9}[hidden]{display:none!important}:focus-visible{outline:3px solid #fff;outline-offset:4px}</style></head><body><main>
<a class="brand" href="/api/site/">Pulse</a><div id="verification-preface"><h1>Help Keep our<br>Community <em>Safe.</em></h1><p>You must be 18+ to use Pulse.</p><p>Age verification helps protect you and our community.</p><p>Start with a selfie. Our verification service Didit will ask for ID if needed.</p></div>
<p id="account"></p><p id="test" hidden>Sandbox test account — this is a test verification.</p><p id="status" role="status" aria-live="polite">Loading your account…</p><p id="error" role="alert"></p>
<section id="start-panel" hidden><h3>Before you begin</h3><p>Use a device with a camera. Didit starts with a selfie to estimate your age and check that you are present. If an ID check is needed, have your own valid identity document ready. Selfie-verified users can also choose Verify with ID on their personal verification page later.</p>
<p>Read ${privacy ? `<a href="${privacy}" target="_blank" rel="noopener noreferrer">Pulse's privacy notice</a> and ` : ""}<a href="https://didit.me/terms/privacy-policy/" target="_blank" rel="noopener noreferrer">Didit's privacy notice</a> before continuing.</p>
<label><input type="checkbox" id="consent"><span>I agree to let Didit use my ID and selfie to verify my age.</span></label><button id="start">Continue to verification</button></section>
<p id="verification-method" hidden></p>
<section id="upgrade-panel" hidden><h2>Verify with ID</h2><p id="upgrade-status" role="status" aria-live="polite"></p><p>Didit will check your identity document and match it to a new selfie. Your current verification stays active while the check is in progress.</p><p>Read ${privacy ? `<a href="${privacy}" target="_blank" rel="noopener noreferrer">Pulse's privacy notice</a> and ` : ""}<a href="https://didit.me/terms/privacy-policy/" target="_blank" rel="noopener noreferrer">Didit's privacy notice</a> before continuing.</p><div id="upgrade-actions"><label><input type="checkbox" id="upgrade-consent"><span>I agree to let Didit use my ID and selfie to verify my age.</span></label><button id="upgrade">Verify with ID</button></div></section>
<section id="mature-panel" hidden><h2>Your content preference</h2><p>Thank you for verifying your age. Verification helps protect you and keep our community safe.</p><p>You can now choose to enable NSFW/Mature Content.</p><label class="toggle-row"><span>Show NSFW/Mature Content (18+)</span><input type="checkbox" role="switch" id="mature"></label><button id="save">Save preference</button><p id="saved" role="status" aria-live="polite"></p></section>
<button id="refresh" hidden>Check verification status</button><a class="button" href="mobile://verification">Return to Pulse</a><small>If the app does not open, switch back to Pulse. You can reopen this page from Account → Age verification.</small>
<script nonce="${nonce}">
const root='/api/verification/web';let csrf='';let busy=false;let pending=false;
const el=id=>document.getElementById(id);
async function request(path,body){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),15000);try{const r=await fetch(root+path,{signal:controller.signal,method:body?'POST':'GET',credentials:'same-origin',headers:{'Content-Type':'application/json','X-Verification-CSRF':csrf},...(body?{body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok){if(r.status===401){pending=false;csrf='';for(const id of ['start-panel','mature-panel','refresh','upgrade-panel','verification-method'])el(id).hidden=true;el('status').textContent='Open this page from your Pulse account.';throw Error('In Pulse, go to Account → Age verification and tap Verify now to open your personal link.');}throw Error(d.error||'Please try again.');}return d;}catch(e){if(e.name==='AbortError')throw Error('The request timed out. Please try again.');throw e;}finally{clearTimeout(timer);}}

function render(d){
const upgradePending=d.upgradeStatus==='pending';const upgradeReview=d.upgradeStatus==='review_needed';
pending=d.status==='pending'||upgradePending;
el('verification-preface').hidden=d.isVerified;
el('start-panel').hidden=d.isVerified||d.status==='review_needed'||(d.upgradeStatus&&d.upgradeStatus!=='not_started');
el('mature-panel').hidden=!d.isVerified;el('mature').checked=!!d.matureContentEnabled;
el('refresh').hidden=!pending&&d.status!=='review_needed'&&!upgradeReview;
el('status').className=d.isVerified?'verified-status':'';
el('status').textContent=d.isVerified?'You’re Verified':d.status==='pending'?'Your verification is in progress.':d.status==='review_needed'?'Your verification needs review. Please contact Pulse support.':d.status==='failed'?'Verification was not approved. You must be 18 or older. Please contact Pulse support if you need help.':'Your age has not been verified.';
el('verification-method').hidden=!d.isVerified;el('verification-method').textContent=d.verificationType==='id'?'Verified with ID':d.verificationType==='selfie'?'Your age was verified with a selfie.':'';
el('upgrade-panel').hidden=!d.isVerified||d.verificationType!=='selfie';
el('upgrade-status').textContent=upgradePending?'Your ID verification is in progress.':upgradeReview?'Your ID verification needs review. Please contact Pulse support.':d.upgradeStatus==='failed'?'Your ID check was not completed or approved. Your selfie verification remains active.':!d.canUpgrade?'ID verification is currently unavailable. Please try again later.':'You can add ID verification to your account.';
el('upgrade-actions').hidden=!d.canUpgrade||upgradeReview;
el('upgrade').textContent=upgradePending?'Continue ID verification':d.upgradeStatus==='failed'?'Try ID verification again':'Verify with ID';
}
async function run(fn){if(busy)return;busy=true;el('error').textContent='';el('refresh').textContent='Checking verification status…';for(const b of document.querySelectorAll('button'))b.disabled=true;try{await fn();}catch(e){el('error').textContent=e.message;if(!csrf)el('status').textContent='Reopen verification from your Pulse account to continue.';}finally{busy=false;el('refresh').textContent='Check verification status';for(const b of document.querySelectorAll('button'))b.disabled=false;}}
el('start').onclick=()=>run(async()=>{if(!el('consent').checked)throw Error('Please read and accept the verification notice first.');const d=await request('/start',{consent:true,consentVersion:'pulse-id-18-v1'});location.assign(d.url);});
el('upgrade').onclick=()=>run(async()=>{if(!el('upgrade-consent').checked)throw Error('Please read and accept the ID verification notice first.');const d=await request('/upgrade',{consent:true,consentVersion:'pulse-id-upgrade-v1'});location.assign(d.url);});
el('save').onclick=()=>run(async()=>{render(await request('/preference',{enabled:el('mature').checked,version:'pulse-mature-v1'}));el('saved').textContent='Preference saved.';});
el('refresh').onclick=()=>run(async()=>{render(await request('/refresh',{}));el('status').textContent+=' Status checked.';});
run(async()=>{const ticket=new URLSearchParams(location.hash.slice(1)).get('ticket');const returning=new URLSearchParams(location.search).has('verificationSessionId');history.replaceState(null,'',location.pathname);if(ticket)await request('/exchange',{ticket});const d=await request('/status');csrf=d.csrf;el('account').textContent='Pulse account '+d.accountId;el('test').hidden=d.environment!=='sandbox';render(d);if(returning)render(await request('/refresh',{}));});
let polls=0;setInterval(()=>{if(pending&&!document.hidden&&polls++<40)run(async()=>render(await request('/refresh',{})));},15000);
</script></main></body></html>`;
}
