import messageSettingsRouter from "./message-settings";
import privacyRouter from "./privacy";
import notificationsRouter from "./notifications";
import accountRouter from "./account";
import userSafetyRouter from "./user-safety";
import partiesRouter from "./parties";
import translationRouter from "./translation";
import { Router, type IRouter } from "express";
import moderationRouter from "./moderation";
import healthRouter from "./health";
import agoraRouter from "./agora";
import streamsRouter from "./streams";
import chatRouter from "./chat";
import directMessagesRouter from "./direct-messages";
import usersRouter from "./users";
import coinsRouter from "./coins";
import mediaPacksRouter from "./media-packs";
import postsRouter from "./posts";
import privateStreamInvitationsRouter from "./private-stream-invitations";

const router: IRouter = Router();

router.use(healthRouter);
router.use(privacyRouter);
router.use(messageSettingsRouter);
router.use(notificationsRouter);
router.use(accountRouter);
router.use(partiesRouter);
router.use(userSafetyRouter);
router.use(translationRouter);
router.use(moderationRouter);
router.use(agoraRouter);
router.use(streamsRouter);
router.use(chatRouter);
router.use(directMessagesRouter);
router.use(usersRouter);
router.use(coinsRouter);
router.use(mediaPacksRouter);
router.use(postsRouter);
router.use(privateStreamInvitationsRouter);

export default router;
