"""Generate the original default gift chime and its native bundle (no dependencies)."""
import base64
import io
import math
import pathlib
import struct
import wave

root = pathlib.Path(__file__).resolve().parents[1]
rate = 24000
samples = []
for i in range(int(rate * 1.8)):
    t = i / rate
    value = 0.0
    for onset, frequency in [(0, 523.251), (0.12, 659.255), (0.24, 783.991)]:
        age = t - onset
        if age >= 0:
            envelope = min(age / 0.012, 1) * math.exp(-age * 4.5)
            value += 0.19 * envelope * (math.sin(2 * math.pi * frequency * age)
                       + 0.2 * math.sin(2 * math.pi * frequency * 2 * age))
    value *= min((1.8 - t) / 0.08, 1)
    samples.append(struct.pack('<h', round(value * 32767)))
buffer = io.BytesIO()
with wave.open(buffer, 'wb') as output:
    output.setnchannels(1)
    output.setsampwidth(2)
    output.setframerate(rate)
    output.writeframes(b''.join(samples))
data = buffer.getvalue()
(root / 'assets/moments/default-gift.wav').write_bytes(data)
(root / 'utils/defaultGiftSound.ts').write_text(
    '// Generated by scripts/generate-default-gift-sound.py. Original synthesized chime.\n'
    'export const DEFAULT_GIFT_SOUND_ID = 731001;\n'
    'export const defaultGiftSoundBase64 = "' + base64.b64encode(data).decode() + '";\n')
