import assert from 'node:assert/strict';
import vm from 'node:vm';
import { build } from 'esbuild';
import { fileURLToPath } from 'node:url';
const dir=fileURLToPath(new URL('..',import.meta.url));
const bundle=await build({entryPoints:[`${dir}/src/lib/verificationPage.ts`],bundle:true,write:false,platform:'node',format:'cjs',logLevel:'silent'});
const module={exports:{}};vm.runInNewContext(bundle.outputFiles[0].text,{module,exports:module.exports});
const html=module.exports.verificationPage('test');
const script=html.match(/<script[^>]*>([\s\S]*?)<\/script>/)[1];
const elements=new Map([...html.matchAll(/id="([^"]+)"/g)].map(m=>[m[1],{hidden:true,disabled:false,textContent:'',checked:false}]));
const buttons=['start','save','refresh'].map(id=>elements.get(id));
let mode='normal';let calls=0;
const state={status:'pending',isVerified:false,matureContentEnabled:false,csrf:'test-csrf',accountId:1,environment:'sandbox'};
const ctx=vm.createContext({document:{getElementById:id=>elements.get(id),querySelectorAll:()=>buttons,hidden:false},location:{hash:'',search:'',pathname:'/api/verification/'},history:{replaceState(){}},URLSearchParams,AbortController,setInterval(){},setTimeout:(fn)=>setTimeout(fn,25),clearTimeout,fetch:async(url,opts)=>{calls++;if(mode==='timeout')return new Promise((_,reject)=>opts.signal.addEventListener('abort',()=>reject(Object.assign(new Error('abort'),{name:'AbortError'}))));return {ok:mode!=='expired',status:mode==='expired'?401:200,json:async()=>state};}});
vm.runInContext(script,ctx);
await new Promise(resolve=>setTimeout(resolve,5));
assert.equal(elements.get('refresh').hidden,false);
assert.equal(elements.get('refresh').disabled,false);
mode='timeout';
const stalled=elements.get('refresh').onclick();
assert.equal(elements.get('refresh').disabled,true);
assert.match(elements.get('refresh').textContent,/Checking/);
await stalled;
assert.equal(elements.get('refresh').disabled,false);
assert.match(elements.get('error').textContent,/timed out/);
mode='normal';
await elements.get('refresh').onclick();
assert.match(elements.get('status').textContent,/Status checked/);
assert.equal(elements.get('error').textContent,'');
mode='expired';
await elements.get('refresh').onclick();
for(const id of ['refresh','start-panel','mature-panel'])assert.equal(elements.get(id).hidden,true);
assert.match(elements.get('error').textContent,/Account → Age verification/);
assert.equal(elements.get('refresh').disabled,false);
assert.equal(calls,4);
console.log('PASS: page script shows refresh progress, recovers after timeout, confirms success, and hides account actions on expiry. Simulated DOM; no visual/device check.');
